# Quick tests of small code chunks

## np.array resize using excel style range

In [117]:
import numpy as np
import pandas as pd
import re

input_path = "sample_data/random1.xls"

filetype = input_path.split(".")[-1]
if filetype == "xlsx" or filetype == "xls" or filetype == "ods":
    df = pd.read_excel(input_path, header=None)
elif filetype == "csv":
    df = pd.read_csv(input_path, sep=",", header=None)
elif filetype == "tsv":
    df = pd.read_csv(input_path, sep="\t", header=None)
else:
    raise TypeError(f"""
                    Format is {filetype} not supported
                    You may want to use:
                    csv
                    tsv
                    xlsx
                    xls
                    ods
                    """)
array = np.asarray(df)


size = "A1:C5"
def resize(array, size):
    cols = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    start = size.split(":")[0]
    end = size.split(":")[-1]
    
    start_column_code = re.findall("[A-Z]", start)
    end_column_code = re.findall("[A-Z]", end)
    
    start_col_idx = len(cols) * (len(start_column_code) - 1) + cols.find(start_column_code[-1])
    end_col_idx = len(cols) * (len(end_column_code) - 1) + cols.find(end_column_code[-1]) + 1
    
    start_row_idx = int("".join(re.findall("[0-9]", start))) - 1
    end_row_idx = int("".join(re.findall("[0-9]", end)))
    
    resized = array[start_row_idx:end_row_idx,
                    start_col_idx:end_col_idx]
    if list(resized):
        return resized
    else:
        raise ValueError(f"Range {size} returns an empty array.")

resized = resize(array, size)
print(resized)

[[0.50314612 0.14238465 0.32661468]
 [0.15058171 0.69183339 0.98404963]
 [0.57774101 0.86280871 0.64289943]
 [0.80767845 0.98864381 0.50551012]
 [0.06271575 0.56241126 0.5195514 ]]


## check if string is empty

In [120]:
s = ""
if s:
    print("not empty")
else:
    print("empty")

empty


In [124]:
import numpy as np
type(np.nan)

float